use egui::Event;
use ratatui_app::key_code::KeyCode;

pub fn key_code_to_char(value: &Event) -> Option<KeyCode> {
    match value {
        Event::Copy => None,
        Event::Cut => None,
        Event::Paste(_) => None,
        Event::Text(char) => {
            if char.chars().count() == 1 {
                Some(KeyCode::Char(char.chars().next().unwrap()))
            } else {
                None
            }
        }
        Event::Key {
            key, pressed: true, ..
        } => match key {
            egui::Key::ArrowDown => Some(KeyCode::Down),
            egui::Key::ArrowLeft => Some(KeyCode::Left),
            egui::Key::ArrowRight => Some(KeyCode::Right),
            egui::Key::ArrowUp => Some(KeyCode::Up),
            egui::Key::Escape => Some(KeyCode::Esc),
            egui::Key::Tab => Some(KeyCode::Tab),
            egui::Key::Backspace => Some(KeyCode::Backspace),
            egui::Key::Enter => Some(KeyCode::Enter),
            egui::Key::Space => None,
            egui::Key::Insert => None,
            egui::Key::Delete => None,
            egui::Key::Home => None,
            egui::Key::End => None,
            egui::Key::PageUp => None,
            egui::Key::PageDown => None,
            egui::Key::Copy => None,
            egui::Key::Cut => None,
            egui::Key::Paste => None,
            egui::Key::Colon => None,
            egui::Key::Comma => None,
            egui::Key::Backslash => None,
            egui::Key::Slash => None,
            egui::Key::Pipe => None,
            egui::Key::Questionmark => None,
            egui::Key::OpenBracket => None,
            egui::Key::CloseBracket => None,
            egui::Key::Backtick => None,
            egui::Key::Minus => None,
            egui::Key::Period => None,
            egui::Key::Plus => None,
            egui::Key::Equals => None,
            egui::Key::Semicolon => None,
            egui::Key::Num0 => None,
            egui::Key::Num1 => None,
            egui::Key::Num2 => None,
            egui::Key::Num3 => None,
            egui::Key::Num4 => None,
            egui::Key::Num5 => None,
            egui::Key::Num6 => None,
            egui::Key::Num7 => None,
            egui::Key::Num8 => None,
            egui::Key::Num9 => None,
            egui::Key::A => None,
            egui::Key::B => None,
            egui::Key::C => None,
            egui::Key::D => None,
            egui::Key::E => None,
            egui::Key::F => None,
            egui::Key::G => None,
            egui::Key::H => None,
            egui::Key::I => None,
            egui::Key::J => None,
            egui::Key::K => None,
            egui::Key::L => None,
            egui::Key::M => None,
            egui::Key::N => None,
            egui::Key::O => None,
            egui::Key::P => None,
            egui::Key::Q => None,
            egui::Key::R => None,
            egui::Key::S => None,
            egui::Key::T => None,
            egui::Key::U => None,
            egui::Key::V => None,
            egui::Key::W => None,
            egui::Key::X => None,
            egui::Key::Y => None,
            egui::Key::Z => None,
            egui::Key::F1 => None,
            egui::Key::F2 => None,
            egui::Key::F3 => None,
            egui::Key::F4 => None,
            egui::Key::F5 => None,
            egui::Key::F6 => None,
            egui::Key::F7 => None,
            egui::Key::F8 => None,
            egui::Key::F9 => None,
            egui::Key::F10 => None,
            egui::Key::F11 => None,
            egui::Key::F12 => None,
            egui::Key::F13 => None,
            egui::Key::F14 => None,
            egui::Key::F15 => None,
            egui::Key::F16 => None,
            egui::Key::F17 => None,
            egui::Key::F18 => None,
            egui::Key::F19 => None,
            egui::Key::F20 => None,
            egui::Key::F21 => None,
            egui::Key::F22 => None,
            egui::Key::F23 => None,
            egui::Key::F24 => None,
            egui::Key::F25 => None,
            egui::Key::F26 => None,
            egui::Key::F27 => None,
            egui::Key::F28 => None,
            egui::Key::F29 => None,
            egui::Key::F30 => None,
            egui::Key::F31 => None,
            egui::Key::F32 => None,
            egui::Key::F33 => None,
            egui::Key::F34 => None,
            egui::Key::F35 => None,
        },
        Event::PointerMoved(_) => None,
        Event::MouseMoved(_) => None,
        Event::PointerButton { .. } => None,
        Event::PointerGone => None,
        Event::Scroll(_) => None,
        Event::Zoom(_) => None,
        Event::CompositionStart => None,
        Event::CompositionUpdate(_) => None,
        Event::CompositionEnd(_) => None,
        Event::Touch { .. } => None,
        Event::MouseWheel { .. } => None,
        Event::WindowFocused(_) => None,
        Event::AccessKitActionRequest(_) => None,
        Event::Screenshot { .. } => None,
        _ => None,
    }
}
