[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.200"
serde_json = "1.0.116"
shared = { path = "../shared" }
strum = "0.26.2"
strum_macros = "0.26.2"
websocket = "0.27.1"

