[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = "0.25.0"
strum_macros = "0.25.2"
itertools = "0.12.1"
enum-map = "2.6.1"
rand = "0.8.5"
serde_json = "1.0.116"
serde = { version = "1.0.200", features = ["serde_derive"] }
