[package]
name = "ratatui-app"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
itertools = "0.12.1"
ratatui = { version = "0.26.1", default-features = false, features = ["unstable"] }
taffy = "0.4.3"
